### PR TITLE
Fix Cagtegories feature

### LINKED ISSUE #13: [Bug] Category ID is the same across all flights
## Problem
- there's a bug that category IDs are the same across all flights
- this may cause issues if users test on multiple flights

## Severity
- medium
    - this seems to have existed since day one
    - this doesn't affect users who test on a single flight

## Work estimate
- one-to-two person-days, including manual tests

### PR DESCRIPTION
**Pull request by kndoshn**
1. Removed the `category: Category?` property from _MenuItem_ model
    - _MenuItem_ had `categoryId: String?` and `category: Category?`, but `category: Category?` wasn't really used
2. Fix prepopulated items
    -  There is a`Prepopulate data` button under the settings page, but it wasn't working correctly
      - `writeStrategy` was `insertIfAbsent`, but the document IDs were just the names of the category
      - means that they couldn't be added to other flights

Fixes #13

### CODE REVIEW

**Comment by kndoshn** [comment]
> This branch did not build for me, with SwiftHEXColors linking failure. Neither did the Env.swift appear to be generated, however the build failure was in the linking phase.

I git-pulled this repository as a new project, and I saw the same issue, but it got fixed after #26.
I'll merge #26 to this branch as soon as it's merged into `main`.

File: iOS/SkyService/Data/DataService/DataService+Prepopulate.swift [hunk 1]
```diff
@@ -323,11 +323,11 @@ extension DataService {
                     "workspaceId": workspaceId,
                     "isCrewOnly": isCrewOnly,
                     "deleted": false
-                ], writeStrategy: .insertIfAbsent)
+                ])
             }
 
             for menuItem in menuItemsData {
-                let _ = try? tx["menuItems"].upsert(menuItem, writeStrategy: .insertIfAbsent)
```
Comment (okdistribute) [inline iOS/SkyService/Data/DataService/DataService+Prepopulate.swift:330]: Should the pre-populated menu items use `insertDefaultWithAbsent`? I'm thinking this might be important because multiple people could prepopulate the app with the same menu items concurrently which would create a lot of extra unintentional metadata.

**Review by okdistribute — CHANGES_REQUESTED** [review]

File: iOS/SkyService/Data/DataService/DataService+Prepopulate.swift (hunk 1 above)
Comment (kndoshn) [reply iOS/SkyService/Data/DataService/DataService+Prepopulate.swift:330]: You're correct - I changed it. thanks!
- [348f360](https://github.com/getditto/demoapp-skyservice/pull/19/commits/348f36099bf824b993cea00fdf05c15e827e9c59)

**Review by okdistribute — APPROVED** [review]
